### ISSUE TITLE
Добавить роутинг по достопримечательностям

### ISSUE THREAD

**Issue by Julia-Lavrova** [heritagemap/frontend-pwa#133]
Добавить возможность скидывать ссылку на ту или иную достопримечательность
- открывать сразу боковую панель с информацией
- переводить пользователя в указанную точку

**Comment by avdeev** [comment]
У меня работает. Закрываю
https://heritagemap.ru/lat/56.54015/lon/43.828419/5230023000
![image](https://user-images.githubusercontent.com/1241671/100755177-f3ccea00-33fc-11eb-8afe-dca522bf8a7b.png)
