### ISSUE TITLE
При переходе к текущему положению не подгружаются объекты

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#159]
При переходе к текущему положению при нажатию на соответствующую кнопку не подгружаются объекты для нового положения карты. Чтобы объекты подгрузились, надо либо изменить зум, либо немного подвинуть карту

**Comment by Julia-Lavrova** [comment]
https://github.com/heritagemap/frontend-pwa/pull/196

**Comment by avdeev** [comment]
Closes via #196 

@evgenykatyshev перепроверь, плиз

**Comment by evgenykatyshev** [comment]
Да, всё работает
