### ISSUE TITLE
Добавить в URL сайта координаты текущего места

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#160]
Добавить в URL сайта координаты текущего места, чтобы можно было давать ссылку не только на объект (пока это тоже нельзя), но и просто на место на карте. Мне кажется, такая фича есть в mapbox из коробки

**Comment by Julia-Lavrova** [comment]
Ну как, мы знаем координаты текущего места, можем в роут добавить его, а по роуту матчить место на карте
Ок, поняла тебя, сделаю

**Comment by evgenykatyshev** [comment]
Ещё зум надо выводить

Я бы предложил вот такой формат URL: heritagemap.ru/<zoom>/<lat, 6 цифр после запятой>/<lon, 6 цифр после запятой>/<knid, если выбран объект>

6 цифр после запятой точно достаточно, 5 — не уверен.

Пример:
heritagemap.ru/12/55.753954/37.949414/5000001897
heritagemap.ru/14/55.753950/37.949400

**Comment by evgenykatyshev** [comment]
На всякий случай уточню, что координаты в URL должны меняться при перемещении карты, а не только при выборе объекта.

**Comment by avdeev** [comment]
@evgenykatyshev Перепроверь, плиз, после деплоя

**Comment by evgenykatyshev** [comment]
1) При выборе точки координаты в адресе не должны меняться на координаты объекта, т. к. они должны соответствовать положению карты.
2) Теперь при перемещение карты панель объекта сама закрывается.


Я ещё подумал, что моё предложение по виду URL два комментария назад плохое. Лучше сделать как в OSM:

Ссылка на объекта:
https://www.openstreetmap.org/way/150568230

Если по ней перейти, то автоматически добавится параметр map с координатами объекта, будет открыта панель и выделен объект. Ссылка станет такой:
https://www.openstreetmap.org/way/150568230#map=19/56.31977/44.00763

Если с открытой панелью подвигать карту, то изменятся координаты в параметре map, но панель объекта останется открытой:
https://www.openstreetmap.org/way/150568230#map=15/56.3102/44.0380

Ссылка на место на карте без выбранного объекта:
https://www.openstreetmap.org/#map=15/56.3102/44.0455

**Comment by Julia-Lavrova** [comment]
Бага была, починила, теперь id сохраняется, координаты меняются вне зависимости.
Но логику с короткой ссылкой на объект `/{id}` отдельно сделаю, там подольше.

**Comment by evgenykatyshev** [comment]
А п. 1 из моего последнего коммента поправишь? Чтоб карта не смещалась, когда ты выбираешь какой-то объект. А то, например, очень неудобно, когда хочешь протыкать группу точек, а после первого же выбранного объекта всё съезжает и ты не помнишь что посмотрел, а что нет.

**Comment by Julia-Lavrova** [comment]
А точно это надо? перемещать карту к точке не нужно?
только руками перемещаем?

**Comment by evgenykatyshev** [comment]
Да, точно.

Я смотрел как сделано у Яндекса, Гугла, 2gis и OSM (у всех одинаково). Если ты открыл карточку объекта на карте, то карта остаётся на месте. И ссылка из карточки копируется с теми координатами, что были у карты в момент копирования. А вот если ты даёшь ссылку на какой-то объект без координат карты, то карта центрируется относительно этого объекта.

**Comment by Julia-Lavrova** [comment]
Ок, сделаю

пн, 25 янв. 2021 г. в 19:03, Evgeny Katyshev <notifications@github.com>:

**Comment by Julia-Lavrova** [comment]
@evgenykatyshev готово

**Comment by evgenykatyshev** [comment]
Потестил в ФФ и Яндексе на ПК и в Хроме на Андроиде. Всё работает.
