### ISSUE TITLE
html-код в описании выводится в виде кода

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#167]
Есть способ оставить только текст внутри тегов, убрав сами теги?

![image](https://user-images.githubusercontent.com/21023515/99715441-f0119d00-2ab7-11eb-8be3-68f0d423f942.png)

**Comment by avdeev** [comment]
Ссылка точку https://heritagemap.ru/lat/57.203843/lon/45.057542/5240259000

**Comment by Julia-Lavrova** [comment]
![Uploading image.png…]()
Так пойдет?

**Comment by Julia-Lavrova** [comment]
<img width="100" alt="Снимок экрана 2020-12-09 в 21 25 44" src="https://user-images.githubusercontent.com/18362544/101671223-42196300-3a65-11eb-8d8f-f0aa1b4c76a4.png">
Так пойдет?

**Comment by evgenykatyshev** [comment]
Думаю, лучше вообще убирать ссылки, оставлять только просто текст. В данном случае, например, ссылка ведёт на служебную страницу Викигида, которая обычным людям вряд ли интересна. Если сложно убрать ссылку, можно прописать ей стили обычного текста, тогда её никто никогда не нажмёт :)

Но, если чё, так точно лучше, чем было.

**Comment by batyrmastyr** [comment]
@Julia-Lavrova а стоит ли вставлять html с возможными скриптами и собственными стилями из сторонних источников?
Гораздо спокойнее вставить такое (утащено из Ангуляра): 
```JavaScript
const tmp = document.createElement("DIV");
tmp.innerHTML = html;
return tmp.textContent
        // Removes the Zero-Width Space, Zero-Width Joiner, Zero-Width No-Break Space, Left-To-Right Mark, and Right-To-Left Mark characters
    .replace(/[\u200B-\u200D\uFEFF\u200E\u200F]/g, '')
    .trim();
```
Защищает [не от всего](https://developer.mozilla.org/ru/docs/Web/API/Element/innerHTML), но хоть что-то.

Кстати, а в каких браузерах проект должен работать?

**Comment by Julia-Lavrova** [comment]
В каких скажешь, во всех проверю, где смогу - починю, я пока только хром смотрю
