### ISSUE TITLE
При первом открытии сайта не грузятся точки памятников

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#187]
1. Открываем Chrome в режиме инкогнито
2. Вбиваем в адресную строку heritagemap.ru, переходим (не двигаем карту)
3. Если браузер запрашивает данные о местоположении, не даём (иначе карта сдвинется)
4. Не двигаем карту, ждём

**Ожидаемый результат**
Загрузятся точки для той локации, которая открылась по дефолту

**Фактический результат**
Ничего не грузится (запросы не отправляются), пока не подвинем карту.

**Comment by Julia-Lavrova** [comment]
https://github.com/heritagemap/frontend-pwa/pull/196

**Comment by avdeev** [comment]
@evgenykatyshev перепроверь, плиз

у меня пофиксилось

**Comment by evgenykatyshev** [comment]
Да, пофиксилось
