### ISSUE TITLE
Убрать ограничение на количество загружаемых на карту объектов

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#50]
Сейчас для текущего вьюпорта загружается число загружаемых объектов ограничено. Максимум штук 50, на глаз, загружается. Подозреваю, что для этого нужно сначала кластеризацию сделать, иначе будет виснуть.

**Comment by evgenykatyshev** [comment]
Хотя, например, на dtp-stat.ru грузится дофига точек, и не виснет.

**Comment by evgenykatyshev** [comment]
Похоже, дело не в лимите точек, а в фиксированном размере bbox в запросе, не зависящим от вьюпорта.

**Comment by Julia-Lavrova** [comment]
Не, я там по области ограничила, но еще будет ограничение в 100 точек у апи, там что полностью от ограничений не откажемся

**Comment by avdeev** [comment]
Ограничения нужны, на плохой сети "в полях" попытка загрузить много точек может окончиться полным провалом :)

Можно лимит увеличить, наверное, или кластеризацию делать на серваке.
Или не грузить точки на мелких масштабах.

**Comment by Julia-Lavrova** [comment]
Закрываем?

**Comment by evgenykatyshev** [comment]
Наверное, пока точки беруться напрямую из апи с лимитом в 100, можно закрыть.
