### ISSUE TITLE
Сохранять последнее положение карты

### ISSUE THREAD

**Issue by evgenykatyshev** [heritagemap/frontend-pwa#51]
Сейчас есть проблема, что при перезагрузке приложения (а на мобильном оно часто происходит при переключении между приложениями) позиция карты сбрасывается на дефолтную — приходится снова искать нужное место.

На популярных сервисах положение сохраняется. Там каждый раз при обновлении координат куку обновляют, как я понимаю.

**Comment by Julia-Lavrova** [comment]
https://github.com/heritagemap/frontend-pwa/commit/bd644b4bf0e72307688099497f48b9550b1806e9
Проверь

**Comment by Julia-Lavrova** [comment]
https://github.com/heritagemap/frontend-pwa/commit/11aed80587313bd975f7c5fd41923801fcf0313e

**Comment by evgenykatyshev** [comment]
Работает
